# .github/workflows/main.yml

name: Test & Build

on:
  workflow_call:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - uses: actions/setup-go@v4
      with:
        go-version-file: ./go.mod
    - run: |
        export PATH=$(go env GOROOT)/misc/wasm:$PATH
        make test

  lint:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          check-latest: true
      - run: |
          export PATH=$(go env GOROOT)/misc/wasm:$PATH
          make lint
